steps:
  - name: 3.9-sapmachine-17
    entrypoint: mvn
    args: ['--version']

  # build production files
  - name: 3.9-sapmachine-17
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]

  # Deploy to google cloud app engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']